version: '3.9'
services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: gopal
      MYSQL_PASSWORD: gopal123
    volumes:
      - mysql-data:/var/lib/mysql
  backend:
    image: nileshdubey404/backend:v1
    container_name: backend
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:8080"
  frontend:
    image: nileshdubey404/frontend:v1
    container_name: frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
volumes:
  mysql-data:
  #to run mysql whole 1gb taken by Mysql.minimum requirment

  #scalling and loadbalancing are the limitations of docker compose containers