FROM node:24 AS builder

WORKDIR /app

RUN cd ..

COPY package*.json ./

# COPY ../package*.json ./

RUN npm install

COPY . .
# COPY ../ ./

RUN npm run build

FROM nginx:alpine

RUN cd ..

COPY nginx/default.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]  
# there should be only one CMD in Whole Docker file
